### ISSUE TITLE
Make logging optional

### ISSUE THREAD

**Issue by WeeJeWel** [foxt/icloud.js#24]
Thank you for this amazing library!

I'm working on a [CLI utility to automate downloading iCloud Drive to a NAS](https://github.com/WeeJeWel/node-icloud-backup).

Can the `console.debug` entries be replaced by the `debug` module, or a `options.debug = console.debug` parameter, so it can be disabled?

Thank you!

**Comment by foxt** [comment]
Fixed in 622f66c6a5994a1583c2cc8be9958ca34da9135d. npm isn't letting me publish right now for some reason so it's not on there just yet.

**Comment by WeeJeWel** [comment]
Wow, that was fast! Thank you! 🙏🏻

**Comment by WeeJeWel** [comment]
@foxt Could you retry publishing to npm please?

**Comment by foxt** [comment]
thanks for the reminder, should be up now.

**Comment by WeeJeWel** [comment]
Awesome, thank you!

**Comment by WeeJeWel** [comment]
There seems to be a new bug:

```
TypeError: this.log is not a function
    at iCloudAuthenticationStore.loadTrustToken (/Users/emile/Git/@weejewel/node-icloud-backup/node_modules/icloudjs/build/auth/authStore.js:49:18)
    at iCloudService.authenticate (/Users/emile/Git/@weejewel/node-icloud-backup/node_modules/icloudjs/build/index.js:164:24)
    at iCloudBackup.authenticate (file:///Users/emile/Git/@weejewel/node-icloud-backup/lib/iCloudBackup.mjs:63:20)
    at async iCloudBackup.backupDrive (file:///Users/emile/Git/@weejewel/node-icloud-backup/lib/iCloudBackup.mjs:84:5)
    at async Promise.all (index 0)
    at async file:///Users/emile/Git/@weejewel/node-icloud-backup/bin/icloud-backup.mjs:30:1
```

**Comment by carloslbello** [comment]
> There seems to be a new bug:
> 
> ```
> TypeError: this.log is not a function
>     at iCloudAuthenticationStore.loadTrustToken (/Users/emile/Git/@weejewel/node-icloud-backup/node_modules/icloudjs/build/auth/authStore.js:49:18)
>     at iCloudService.authenticate (/Users/emile/Git/@weejewel/node-icloud-backup/node_modules/icloudjs/build/index.js:164:24)
>     at iCloudBackup.authenticate (file:///Users/emile/Git/@weejewel/node-icloud-backup/lib/iCloudBackup.mjs:63:20)
>     at async iCloudBackup.backupDrive (file:///Users/emile/Git/@weejewel/node-icloud-backup/lib/iCloudBackup.mjs:84:5)
>     at async Promise.all (index 0)
>     at async file:///Users/emile/Git/@weejewel/node-icloud-backup/bin/icloud-backup.mjs:30:1
> ```

I am also getting this error on 1.6.1.

**Comment by MarSoft** [comment]
The patch results in an error when trying to login: Uncaught TypeError: this.log is not a function
Because the log function is declared on iCloudStore but not on iCloudAuthenticationStore.

**Comment by foxt** [comment]
hi all, apologies it took so long,

can you try again with 1.6.2


(and in the meantime i'll see if i can refactor and enable ts strict mode 😬)
